version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always

volumes:
  dbdata:
