name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io
          docker --version

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.DB_USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT}}" >> .env
          echo "✅ .env file created:"
          cat .env

      - name: Run PostgreSQL Container
        run: |
          docker run -d \
            --name postgres \
            --env-file .env \
            -p 5432:5432 \
            postgres:16

      - name: Verify Running Containers
        run: docker ps -a

      - name: Wait for Postgres to be Ready
        run: |
          echo "Waiting for Postgres to be ready..."
          for i in {1..30}; do
            if docker exec postgres pg_isready -U ${{ secrets.DB_USER }}; then
              echo "✅ Postgres is ready!"
              exit 0
            fi
            echo "Still waiting..."
            sleep 2
          done
          echo "❌ Postgres did not become ready in time. Logs:"
          docker logs postgres || true
          exit 1

      - name: Run Redis Container
        run: |
          docker run -d \
            --name redis \
            -p 6379:6379 \
            redis:latest

      - name: Wait for Redis to be Ready
        run: |
          echo "Waiting for Redis to be ready..."
          for i in {1..30}; do
            # Якщо Redis готовий, redis-cli ping поверне "PONG"
            if docker exec redis redis-cli ping | grep "PONG"; then
              echo "✅ Redis is ready!"
              exit 0
            fi
            echo "Still waiting..."
            sleep 2
          done
          echo "❌ Redis did not become ready in time. Logs:"
          docker logs redis || true
          exit 1

      - name: Shutdown PostgreSQL
        run: |
          docker stop postgres
          docker rm postgres

      - name: Shutdown Redis
        run: |
          docker stop redis
          docker rm redis

      - name: Stop Docker Service
        run: sudo systemctl stop docker
